### ISSUE TITLE
test functionality to change the config to use multiple google sheets (kano and bauchi)

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/direct-delivery#213]

**Comment by janetbutts** [comment]
@janetbutts to get template for bauchi

**Comment by janetbutts** [comment]
Emailed m moreland and adamu lewan, reminding them to post a sample/moc sheet.

**Comment by janetbutts** [comment]
Google sheet at:  https://docs.google.com/spreadsheets/d/1iHeB-qd5vZcRmZdV8p5yYoBR23R60Wc5oQmnIVPFslU/edit#gid=1200386844

**Comment by jofomah** [comment]
@janetbutts i have tested a copy of Bauchi Delivery Sheet: https://docs.google.com/spreadsheets/d/1NTqsDg94NqxctEyQQJ4980VLp2HfZ9CsyyDqwLBGrYk/edit#gid=1200386844

i discovered the following:

1. I was able to import Delivery document and KPI correctly;
2. Logged in as a Bauchi driver (basheer) and i saw daily schedule.
3. Couldn't Deliver items because facility ids(hfhta_code)  were not set, i know this won't be the cause in when we deploy. 

Apart from point 3, above, i didn't notice anything else. But i will like to re-test when the template has been completed.

**Comment by janetbutts** [comment]
@mfcm , can you please take a look at jideobi's feedback? please let us know when these issues will be resolved so we can run another round of tests.

**Comment by janetbutts** [comment]
Blocked. PO does not have google sheet ready.

**Comment by jofomah** [comment]
@janetbutts i have tested this again after Health Facility codes were added to the Google Sheet.

Everything work fine so far and syncs to copy of the sheet see: https://docs.google.com/spreadsheets/d/1HqYAgB3O9b8jaCUKnvZwAx2C8pr79KwlA2hjemQcU_A/edit#gid=1200386844

But:

1. We need to create use unique driver ids for e.g both Kano and Bauchi have driver by name Bashir, this made the importer to pick the first Bashir email (Kano driver) maybe we should address this by assigning different unique names e.g State Code-Driver Name.

Will there be need for further testing by Yusuf?
